# Imports

In [1]:
import pickle
import pandas as pd
import geopandas as gpd

# Load Raw Data

In [8]:
europe = pd.read_pickle("../data/europe.p").to_crs("EPSG:4326")
europe_data = pd.read_pickle("../data/gdf_europe.p").to_crs("EPSG:4326")

/home/ak/.miniconda3/envs/class12/lib/python3.7/site-packages/pyproj/crs/crs.py:68: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
/home/ak/.miniconda3/envs/class12/lib/python3.7/site-packages/pyproj/crs/crs.py:68: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))

## Replace target coordinates by target countries polygons

In [12]:
res_intersect_europe = gpd.overlay(europe_data, europe, how='intersection')
# Basically checks for each geometry in "europe_data" (target coordinates) 
# if intersects with geometry of "europe" (country)
# -> Merges both dataframes and keeps country polygon instead of target coordinates
res_intersect_europe.head()

In [17]:
# Set index to country name so we can directly insert data grouped by country name
europe.set_index("name", inplace=True, drop=False)

In [26]:
for year in range(1939, 1946):
    subset = res_intersect_europe.loc[res_intersect_europe['year'] == year]
    europe[f"attacks_{year}"] = subset.groupby("name")["Mission ID"].count()
    europe[f"explosives_weight_{year}"] = subset.groupby("name")["High Explosives Weight (Tons)"].sum()
europe[f"attacks_all"] = res_intersect_europe.groupby("name")["Mission ID"].count()
europe[f"explosives_weight_all"] = res_intersect_europe.groupby("name")["High Explosives Weight (Tons)"].sum()
europe.fillna(0, inplace=True)

# German Bundeslaender

In [38]:
from pathlib import Path
import fiona
bl = gpd.read_file('../data/vg2500_geo84.zip').to_crs("EPSG:4326")

bl.rename({"GEN": "name"}, axis=1, inplace=True)
bl.rename({"GEN": "name", inplace=True)

In [39]:
res_intersect_bl = gpd.overlay(europe_data, bl, how='intersection')

In [40]:
for year in range(1939, 1946):
    subset = res_intersect_bl.loc[res_intersect_bl['year'] == year]
    bl[f"attacks_{year}"] = subset.groupby("name")["Mission ID"].count()
    bl[f"explosives_weight_{year}"] = subset.groupby("name")["High Explosives Weight (Tons)"].sum()
bl[f"attacks_all"] = res_intersect_bl.groupby("name")["Mission ID"].count()
bl[f"explosives_weight_all"] = res_intersect_bl.groupby("name")["High Explosives Weight (Tons)"].sum()
bl.fillna(0, inplace=True)

In [49]:
bl

,USE,RS,RS_ALT,name,SHAPE_LENG,SHAPE_AREA,geometry,attacks_1939,explosives_weight_1939,attacks_1940,...,attacks_1942,explosives_weight_1942,attacks_1943,explosives_weight_1943,attacks_1944,explosives_weight_1944,attacks_1945,explosives_weight_1945,attacks_all,explosives_weight_all
0,2,02,020000000000,Hamburg,1.752538e+05,7.605398e+08,"MULTIPOLYGON (((10.19114 53.72299, 10.18210 53...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,03,030000000000,Niedersachsen,2.016496e+06,4.771641e+10,"MULTIPOLYGON (((8.68962 53.87999, 8.69297 53.8...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,04,040000000000,Bremen,1.549716e+05,4.054809e+08,"MULTIPOLYGON (((8.52976 53.21640, 8.55399 53.2...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2,05,050000000000,Nordrhein-Westfalen,1.352108e+06,3.404727e+10,"POLYGON ((8.66673 52.52149, 8.70289 52.50053, ...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2,06,060000000000,Hessen,1.105093e+06,2.109232e+10,"POLYGON ((9.50560 51.62777, 9.50842 51.62712, ...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2,07,070000000000,Rheinland-Pfalz,9.106504e+05,1.983491e+10,"POLYGON ((7.84657 50.87861, 7.85901 50.87733, ...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2,08,080000000000,Baden-Württemberg,1.298892e+06,3.580140e+10,"MULTIPOLYGON (((9.64634 49.77782, 9.63806 49.7...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2,09,090000000000,Bayern,2.046039e+06,7.055007e+10,"POLYGON ((10.47207 47.56964, 10.47319 47.57081...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2,10,100000000000,Saarland,2.829108e+05,2.578542e+09,"POLYGON ((7.06853 49.62349, 7.08023 49.61196, ...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2,11,110000000000,Berlin,1.807512e+05,8.864801e+08,"POLYGON ((13.61192 52.54332, 13.62461 52.53797...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2,12,120000000000,Brandenburg,1.295460e+06,2.965390e+10,"POLYGON ((13.87357 53.47515, 13.91610 53.45652...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2,13,130000000000,Mecklenburg-Vorpommern,1.780981e+06,2.304468e+10,"MULTIPOLYGON (((12.66717 54.44292, 12.67209 54...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2,14,140000000000,Sachsen,9.792943e+05,1.840164e+10,"POLYGON ((12.90084 51.64699, 12.91309 51.64488...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2,15,150000000000,Sachsen-Anhalt,9.490968e+05,2.049498e+10,"POLYGON ((11.63624 53.00680, 11.64091 53.00601...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2,16,160000000000,Thüringen,9.619427e+05,1.617853e+10,"POLYGON ((10.86498 51.62927, 10.89515 51.61114...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2,01,010000000000,Schleswig-Holstein,1.217256e+06,1.585743e+10,"MULTIPOLYGON (((8.44703 55.05034, 8.46057 55.0...",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# German Landkreise

In [42]:
kreise = gpd.read_file('../data/vg2500_krs.zip').to_crs("EPSG:4326")
kreise.rename({"GEN": "name"}, axis=1, inplace=True)

In [43]:
res_intersect_kreise = gpd.overlay(europe_data, kreise, how='intersection')

In [44]:
for year in range(1939, 1946):
    subset = res_intersect_kreise.loc[res_intersect_kreise['year'] == year]
    kreise[f"attacks_{year}"] = subset.groupby("name")["Mission ID"].count()
    kreise[f"explosives_weight_{year}"] = subset.groupby("name")["High Explosives Weight (Tons)"].sum()
kreise[f"attacks_all"] = res_intersect_kreise.groupby("name")["Mission ID"].count()
kreise[f"explosives_weight_all"] = res_intersect_kreise.groupby("name")["High Explosives Weight (Tons)"].sum()
kreise.fillna(0, inplace=True)

In [48]:
europe.to_pickle("../data/europe_attacks.p")
bl.to_pickle("../data/bl_attacks.p")
kreise.to_pickle("../data/kreise_attacks.p")

In [59]:
res_intersect_kreise.to_pickle("../data/kreise_full.p")

In [75]:
res_intersect_kreise

,Mission ID,Mission Date,Country,Aircraft Series,Target Country,Target City,Target Type,Target Industry,Target Latitude,Target Longitude,...,month,day,Altitude (meters),USE,RS,RS_ALT,name,SHAPE_LENG,SHAPE_AREA,geometry
0,12,1943-08-15,GREAT BRITAIN,LGT,GERMANY,BERLIN,CITY AREA,CITIES TOWNS AND URBAN AREAS,52.53,13.42,...,8,15,7620.00,4,11000,110000000000,Berlin,180751.203631,8.864801e+08,POINT (13.42000 52.53000)
1,13,1943-08-15,GREAT BRITAIN,LGT,GERMANY,BERLIN,CITY AREA,CITIES TOWNS AND URBAN AREAS,52.53,13.42,...,8,15,7620.00,4,11000,110000000000,Berlin,180751.203631,8.864801e+08,POINT (13.42000 52.53000)
2,652,1943-08-17,GREAT BRITAIN,LGT,GERMANY,BERLIN,CITY AREA,CITIES TOWNS AND URBAN AREAS,52.53,13.42,...,8,17,8534.40,4,11000,110000000000,Berlin,180751.203631,8.864801e+08,POINT (13.42000 52.53000)
3,653,1943-08-17,GREAT BRITAIN,LGT,GERMANY,BERLIN,CITY AREA,CITIES TOWNS AND URBAN AREAS,52.53,13.42,...,8,17,8534.40,4,11000,110000000000,Berlin,180751.203631,8.864801e+08,POINT (13.42000 52.53000)
4,1240,1943-08-19,GREAT BRITAIN,LGT,GERMANY,BERLIN,CITY AREA,CITIES TOWNS AND URBAN AREAS,52.53,13.42,...,8,19,8534.40,4,11000,110000000000,Berlin,180751.203631,8.864801e+08,POINT (13.42000 52.53000)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57287,170870,1944-07-20,USA,GB24,GERMANY,COBURG,CITY AREA,CITIES TOWNS AND URBAN AREAS,50.27,10.97,...,7,20,NaN,4,09463,094630000000,Coburg,33448.212208,4.399703e+07,POINT (10.97000 50.27000)
57288,170871,1944-07-20,USA,GB24,GERMANY,COBURG,CITY AREA,CITIES TOWNS AND URBAN AREAS,50.27,10.97,...,7,20,NaN,4,09463,094630000000,Coburg,33448.212208,4.399703e+07,POINT (10.97000 50.27000)
57289,170872,1944-07-20,USA,B24,GERMANY,COBURG,CITY AREA,CITIES TOWNS AND URBAN AREAS,50.27,10.97,...,7,20,NaN,4,09463,094630000000,Coburg,33448.212208,4.399703e+07,POINT (10.97000 50.27000)
57290,176813,1945-02-14,None,B17,GERMANY,SONNEBERG,None,"""RR INSTALLATIONS, TRACKS, MARSHALLING YARDS...",50.33,11.17,...,2,14,7193.28,4,16072,160720000000,Sonneberg,124091.547274,4.345114e+08,POINT (11.17000 50.33000)
57291,176824,1945-02-14,None,B17,GERMANY,SONNEBERG,None,"""RR INSTALLATIONS, TRACKS, MARSHALLING YARDS...",50.33,11.17,...,2,14,6035.04,4,16072,160720000000,Sonneberg,124091.547274,4.345114e+08,POINT (11.17000 50.33000)